language: ruby
rvm:
- 2.1.5
env:
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake
before script:
- cp config/database.yml.sample config/database.yml
- psql -c 'create databse pm_test' -U postgresuser